app_launcher_cmd = "rofi -show drun" 
clipboard_cmd = "cliphist list | rofi -dmenu | cliphist decode | wl-copy"

[modules]
left = [ "WindowTitle"  ]
center = [ "Workspaces", "AppLauncher" ]
right = [ "Weather", "Clipboard", "MediaPlayer", "Tray", "SystemInfo", [ "Clock", "Privacy", "Settings" ] ]

[system_info]
indicators = [ "Cpu", "Memory", "Temperature" ]

[system_info.cpu]
warn_threshold = 60
alert_threshold = 80

[system_info.memory]
warn_threshold = 70
alert_threshold = 85

[system_info.disk]
warn_threshold = 80
alert_threshold = 90

[system_info.temperature]
warn_threshold = 60
alert_threshold = 80

[appearance]
style = "Solid"
scale_factor = 1

primary_color = "#7aa2f7"
success_color = "#9ece6a"
text_color = "#a9b1d6"

workspace_colors = [ "#7aa2f7", "#9ece6a" ]

[appearance.danger_color]
base = "#f7768e"
weak = "#e0af68"

[appearance.background_color]
base = "#1a1b26"
weak = "#24273a"
strong = "#414868"

[appearance.secondary_color]
base = "#0c0d14"

[media_player]
max_title_length = 50

[[CustomModule]]
name = "Weather"
command = "xdg-open 'https://open-meteo.com/en/docs'"
listen_cmd = "~/.config/ashell/weather.sh"
